# Generated by Django 4.1 on 2022-08-16 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кампус',
                'verbose_name_plural': 'Кампусы',
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, null=True, verbose_name='Отчество')),
                ('lastname', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('login', models.CharField(max_length=25, verbose_name='Логин')),
                ('campus', models.IntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.role')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='SchoolObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('object_desc', models.CharField(max_length=255, null=True, verbose_name='Описание')),
                ('object_image', models.BinaryField(null=True, verbose_name='Изображение')),
                ('object_floor', models.IntegerField(verbose_name='Этаж')),
                ('object_room', models.CharField(max_length=255, verbose_name='Помещение')),
                ('object_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.campus')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.objecttype')),
            ],
            options={
                'verbose_name': 'Объект бронирования',
                'verbose_name_plural': 'Объекты бронирования',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Начало бронирования')),
                ('end', models.DateTimeField(verbose_name='Конец бронирования')),
                ('school_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.schoolobject')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
