# Generated by Django 4.1 on 2022-08-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_user_campus_alter_user_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата бронирования'),
        ),
    ]
