# Generated by Django 4.1 on 2022-08-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_booking_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolobject',
            name='object_role',
            field=models.ManyToManyField(to='bot.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='bot_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram ID'),
        ),
    ]
