# Generated by Django 4.1 on 2022-08-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_schoolobject_object_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolobject',
            name='object_role',
            field=models.ManyToManyField(related_name='school_objects', to='bot.role', verbose_name='Права доступа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.campus', verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=25, null=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.role', verbose_name='Role'),
        ),
    ]
